### ISSUE TITLE
Questions regarding .tlog files

### ISSUE THREAD

**Issue by manu-st** [playscale/stashed.io#13]
I'm trying to understand a build failure that I had today. I'm not sure it is related to the use of stashed.io but I wanted to understand better what is happening. For some reason, `msbuild` did not recompile a .cpp files that it should have compiled. To be simple, that file `a.cpp` includes indirectly `b.h` which was modified along with `b.cpp`. The file`b.cpp` was recompiled but not `a.cpp`. Note that the project compiled successfully before we made a change to `b.h` and `b.cpp`.

After some research, it seems that the dependencies for that file (stored in `cl.read.1.tlog` file) were missing a few entries for `a.cpp` which could explain why msbuild failed to recompile it. I understand that the `tlog` file is generated by `cl.exe` and was wondering if somehow the process for creating those .tlog files is impacted by the use of stashed.io.

Thanks for any suggestion on what could be the issue here.

**Comment by jsmouret** [comment]
Internally msbuild wraps cl.exe with a software called Tracker.exe. From what we saw, it seems to catch file open calls from cl.exe to generate the tlog files.
When Stashed detects that it is run by Tracker.exe, it simulates open calls so that tlog files are correct.

Was there anything special about the missing included file?

**Comment by manu-st** [comment]
At first glance, there doesn't seem to be anything special about this header file.

**Comment by jsmouret** [comment]
Seems fixed since 1.4.5
