### ISSUE TITLE
Various linker issues

### ISSUE THREAD

**Issue by kwaegel** [playscale/stashed.io#27]
I'm trying to build a relative large project, and I keep getting linker errors that prevent a complete build. I'm getting a mixture of ` [my_file].obj : fatal error LNK1318: Unexpected PDB error; OK (0) ''` for various individual files, and `LINK : fatal error LNK1102: out of memory` for the entire library.

I've tried deleting and regenerating the project files from CMake, but no change.

This is a private code base, so I'm not sure of a good way to give you a reproducible test case.

Environment: Win10, VS `14.16.27023`, x64_x64 toolset (other toolsets have the same issue).

**Comment by Justin-Randall** [comment]
This is an unfortunate side effect of how MS tools generate debug info with certain flags passed to CL. In order to cache those outputs, several smaller PDBs are generated, which is fine for all but very large projects.

If possible, try using Z7 to generate debug information. It will still generate PDBs, but in a format and manner that does not consume so much memory.

See: 
https://github.com/playscale/stashed.io/wiki/PDB-and-PCH-generation
https://github.com/playscale/stashed.io/wiki/PDB

Specifically: https://github.com/playscale/stashed.io/wiki/PDB#limitation
