### ISSUE TITLE
As a new user, I have no idea how this tool works and if it is useful to my company

### ISSUE THREAD

**Issue by mmatrosov** [playscale/stashed.io#28]
I am looking for a way to speed up builds in our company. I stumbled upon your project. I would like to understand how it works and what impact it might have on our workflow. I went through all the materials I've found on stashed.io site and on github wiki (there weren't many), and I still have no idea about how it works. Only some high-level understanding, that it _somehow_ generates a local cache, which might be _somehow_ pulled by others compiling the same solution.

* What _exactly_ do I need to do to start using it? If it is just install, next, next, how exactly is it integrated in the build from Visual Studio?
* Does it work if I build with MSBuild from Visual Studio Command Prompt?
* Do you cache PCH? It has a bunch of absolute paths encoded into it, did you manage to make it applicable for another physical location?
* Does it work well with incremental builds? I.e. if I change some files relative to the build I have a cache for, will it correctly rebuild only changed files?
* How is it going to work if I run the build using Atlassian Bamboo with its custom build task "Visual Studio 2017"?
* How exactly does it discover computers on the network? Does it need a dedicated server? Does it operate peer-to-peer?
* What is the impact on the network, what amount of data is transferred?
* How exactly does it matches the VS solutions? We have dozens of VS solutions in our company, how is it going to understand which ones have the cache and which ones do not?
* How it understands which files were updated relative to the cache on another computer? We might use the same commit in the same repo, but we have different time stamps of the local files. How does stashed handle this?
* We have the same local projects compiled in scope of different solutions. Is it ok?
* We have the same solutions checked out multiple times on the same local machine in different directories. Will stashed be able to reuse results of the build of one solution to build another?
* What is the size of the local cache comparing to the size of produced binaries? To the size of intermediate files generated by VS?
* How do I control size of the local cache? Can I specify its location? Can I limit the number of cached entries for a single solution? Total number of entries for several solutions? Total size of the cache?
* We rely heavily on code generation and custom targets in our builds. We use some post-build steps and again custom targets to copy specific files to output. Do you handle this case?

Our company has over 100 C++ developers. I suppose you should be interested in having us purchasing your subscription. But how should I assess applicability of your tool when you do not provide any technical information?..

**Comment by Justin-Randall** [comment]
Stashed will intercept calls to CL.exe, examine the command line, environment and source data to quickly generate a hash. If the command line has an unsupported option, it will early out and invoke the compiler. It will query the local cache looking for a match. If it finds one, it will hard-link if the cache entry is on the same physical drive as the requsted output, otherwise it will make a copy. If no entry exists locally, it will make a quick query over the network. If there is a cache hit, the output is copied to the target and cached locally. If there are no cache entries, the compiler is invoked and the output is placed in the cache for future use.

Stashed is intended to solve the same problems that ccache does for other platforms. The Microsoft compiler tools, being what they are, is the sole reason there is no such thing as ccache for MSVC. There is much more complexity in how the Microsoft compiler tools work, which is why Stashed was created in the first place.

One of the core design principles is that Stashed should not impose a lot of administrative overhead on individual programmers. It should be install-and-go with no configuration or intervention required.

> - What exactly do I need to do to start using it? If it is just install, next, next, how exactly is it integrated in the build from Visual Studio?
> - Does it work if I build with MSBuild from Visual Studio Command Prompt?
> - How is it going to work if I run the build using Atlassian Bamboo with its custom build task "Visual Studio 2017"?
> - How exactly does it matches the VS solutions? We have dozens of VS solutions in our company, how is it going to understand which ones have the cache and which ones do not?

Just install it and go. It acts as a front-end for CL.exe, so MSBuild and Visual Studio will take advantage of it.

> - Do you cache PCH? It has a bunch of absolute paths encoded into it, did you manage to make it applicable for another physical location?

In some circumstances, yes. See https://github.com/playscale/stashed.io/wiki/PDB-and-PCH-generation

> - Does it work well with incremental builds? I.e. if I change some files relative to the build I have a cache for, will it correctly rebuild only changed files?

It will not cache this kind of target, so you will get the same behavior as you expect without Stashed.

> - How exactly does it discover computers on the network? Does it need a dedicated server? Does it operate peer-to-peer?

At the moment, it is peer to peer discovery using zeroconf/mdns. Once a Stashed instance is discovered, it will advertise to its peers. Subnet spanning will work if a workstation is on two subnets (e.g. a dev network and perhaps a build farm).

> - What is the impact on the network, what amount of data is transferred?

A hash request is submitted, and if there is a cache hit over the network, the job output is returned. It periodically sends discovery requests to coordinate with other instances of Stashed on the same subnet. It will advertise the list of known Stashed-capable hosts if there is a change in availability.

> - How it understands which files were updated relative to the cache on another computer? We might use the same commit in the same repo, but we have different time stamps of the local files. How does stashed handle this?

There is a content hash of the inputs (source files, headers, command line options and environment variables that affect the build output).

> - We have the same local projects compiled in scope of different solutions. Is it ok?
> - We have the same solutions checked out multiple times on the same local machine in different directories. Will stashed be able to reuse results of the build of one solution to build another?

Sadly, no. It would seem straightforward, but the devil is in the details. It is a work in progress.

> - What is the size of the local cache comparing to the size of produced binaries? To the size of intermediate files generated by VS?
1 to 1 for output (so Stashed can create a hard link for files on the same physical drive). Book-keeping for the cache is all compressed.

> - How do I control size of the local cache? Can I specify its location? Can I limit the number of cached entries for a single solution? Total number of entries for several solutions? Total size of the cache?

This can be done through the dashboard, or the command line using curl (for CLI build systems that want to control it).

> - We rely heavily on code generation and custom targets in our builds. We use some post-build steps and again custom targets to copy specific files to output. Do you handle this case?

It should not be a problem. If the code generation feeds the same source to CL between builds, it has a chance to be cached and re-used.

**Comment by mmatrosov** [comment]
Thanks a lot for an elaborated answer! Let me clarify it a little bit.

> Stashed will intercept calls to CL.exe

How exactly does it do it? Could there be any issues with antivirus software? We use TrendMicro.

> It will not cache this kind of target, so you will get the same behavior as you expect without Stashed.

Imagine I'm doing a build for wich Stashed has a cache. It builds fast. Then I make a small change to my code and compile it. Obviously, Stashed does not have a cache for this new build. So I suppose it will abandon control to `cl.exe`. Normally I would `cl.exe` to make an incremental build. But it needs all the intermediate files to do so, which it does not have, since the build was using Stashed cache. Does that mean, that the full build will occur in this case?

> There is a content hash of the inputs (source files, headers, command line options and environment variables that affect the build output).

Does this mean, that you do not fetch any information from VCS in any way?

> Sadly, no. It would seem straightforward, but the devil is in the details. It is a work in progress.

Ok. I understand that this is a complicated process. However, it does not fit into my vision of how the tool works. Please consider the following scenario. Alice has a repo with our solution checked out in her two local folders, and Bob has the same repo checked out on the same revision in his local folder.

1. Alice builds solution in local folder 1
2. Alice builds solution in local folder 2. According to your explanation, Stashed cannot use cache from the build on step 1.
3. Bob builds solution in his local folder. Seems like this is a classical example, and Stashed should reuse Alice's cache.
4. Alice builds solution in local folder 2, again. And seems like this is a classical example, and Bob's cache should be reused.

Could you please explain, how comes that Stashed cannot reuse cache on step 2, but can do it on step 4? Does this mean, that having Bob as an intermediate cache provider helps Alice to reuse her cache between different versions of the same solution?..

**Comment by Justin-Randall** [comment]
> > Stashed will intercept calls to CL.exe

> How exactly does it do it? 

Since paths are often modified and lead to no small amount of headaches, CL.exe is renamed to cl.original.exe and stashed installs itself as CL.exe for supported platforms. It tries to early-out as quikly as possible for cases where the cache would not be helpful and invokes cl.exe itself. It should behave exactly as if it were never there.

> Could there be any issues with antivirus software? We use TrendMicro.

Stashed is certified by Microsoft's CA (there is a process in place where signing keys are not issued without an audit, Stashed was submitted and approved at launch), so as long as your AV software considers signed and trusted certificates, there should be no issue. 

> Imagine I'm doing a build for which Stashed has a cache. It builds fast. Then I make a small change to my code and compile it. Obviously, Stashed does not have a cache for this new build. So I suppose it will abandon control to cl.exe. Normally cl.exe would make an incremental build. But it needs all the intermediate files to do so, which it does not have, since the build was done using Stashed cache. Does this mean, that the full build will occur in this case?

Not sure exactly what is meant here. If you mean edit-and-continue with .idb files, there would be no difference as the cache would not have been used in the first place. Otherwise, the object files and other output retrieved from the cache are still where MSBuild or whichever build system tracks such dependencies left them and the incremental build will proceed, only compiling the changed inputs. The build system should not even bother to try to compile source files if the object output is already in place. It would behave as you would expect.

> > There is a content hash of the inputs (source files, headers, command line options and environment variables that affect the build output).

> Does this mean, that you do not fetch any information from VCS in any way?

Stashed only concerns itself with CL.exe. If it works with CL.exe, it should work with Stashed, with the only negative effects being that there is a cache miss in some cases, so it behaves just as if Stashed were not even installed.

> > Sadly, no. It would seem straightforward, but the devil is in the details. It is a work in progress.

> Ok. I understand that this is a complicated process. However, it does not fit into my vision of how the tool works. Please consider the following scenario. Alice has a repo with our solution checked out in her two local folders, and Bob has the same repo checked out on the same revision in his local folder.

> Alice builds solution in local folder 1
> Alice tries to build solution in local folder 2. According to your explanation, Stashed cannot use cache from the build on step 1. Alice cancels the build.
Bob builds solution in his local folder. Seems like this is a classical example, and Stashed should reuse Alice's cache.
> Alice builds solution in local folder 2, again. And seems like this is a classical example, and Bob's cache should be reused.
> Could you please explain, how comes that Stashed cannot reuse cache on step 2, but can do it on step 4? Does this mean, that having Bob as an intermediate cache provider helps Alice to reuse her cache between different versions of the same solution?..

This only has to do with how build systems, symbol generation, certain expansions and object file headers end up encoding and using full paths. If the paths are identical, there should be cache hits.

Stashed also uses and LRU, so if Alice has builds in 2 different folders, both builds are cached as they are (hash-wise) totally different jobs. The oldest outputs are eventually evicted (so if Bob has not sync'd with source control, and Alice still has a previous version of the output in the LRU cache, Bob still benefits from Alice's old work).

It will be nice to better support relative paths. That leads to some really bizarre behavior for debugging as PDBs encode source paths. This can be overridden. We are looking for creative ways to solve this without 1) requiring a bunch of manual/administrative intervention by programmers and 2) not slowing things down by trying to do clever or complex edits of object files on the fly (which could then lead to all sorts of problems). Stashed should first be correct and behave as if it was never there, and second, actually save a lot of time for programmers when it is installed. 

This is one of the most requested features as many developers use a Perforce-style branch workflow instead of a git-style branch workflow.

Best practice at the moment, and one we would like to find a good fix for, is to use same path inputs. This can be done using links on the developer filesystem that point to different locations. It is less than ideal because the workaround still requires manual intervention by a programmer to get the most benefits from the cache.

**Comment by mmatrosov** [comment]
> Stashed also uses and LRU, so if Alice has builds in 2 different folders, both builds are cached as they are (hash-wise) totally different jobs.

> Best practice at the moment, ..., is to use same path inputs.

Does this mean that in order for Stashed to work at all, Bob needs to have his solution files stored at exactly the same aboslute path?

> This is one of the most requested features as many developers use a Perforce-style branch workflow instead of a git-style branch workflow.

I do not know, how Perforce works, we use git. Could you please explain what do you mean by this sentence?

**Comment by Justin-Randall** [comment]
> > Stashed also uses and LRU, so if Alice has builds in 2 different folders, both builds are cached as they are (hash-wise) totally different jobs.

> > Best practice at the moment, ..., is to use same path inputs.

> Does this mean that in order for Stashed to work at all, Bob needs to have his solution files stored at exactly the same aboslute path?

Yes. Alternatively, you can also use NTFS links (like symlinks or hard links on UN*X filesystems). 

> > This is one of the most requested features as many developers use a Perforce-style branch workflow instead of a git-style branch workflow.

> I do not know, how Perforce works, we use git. Could you please explain what do you mean by this sentence?

Switching branches in perforce usually means using a completely different, full copy of the project on a developer's filesystem. It is slow and takes up a lot of space. Switching branches in git is done quickly and in-place on the filesystem. Stashed works well with this workflow since a hot cache is properly still mostly hot after switching branches with git.

**Comment by mmatrosov** [comment]
> Yes. Alternatively, you can also use NTFS links (like symlinks or hard links on UN*X filesystems).

Wow. That's a bummer. That was the main reason I started to look for a ready tool, because we do not have build paths unified, and symlink/subst is not always convenient. Thanks for making it clear. I suggest you adding this to the documentation.
